make form
mujohn26/html-form pull request #2
Opened 2020-05-06 09:31 UTC by mujohn26

#### What does this PR do?
- Html input form
#### Description of Task to be completed?
- The added header of the page
-  Added page icons
- added form to the page
#### How should this be manually tested?
- clone the repository
- open index.html in your browser

#### Any background context you want to provide?
- N/A

#### Screenshots (if appropriate)
<img width="1439" alt="Screen Shot 2020-05-06 at 11 30 16" src="https://user-images.githubusercontent.com/52497006/81162192-1133f580-8f8d-11ea-8523-c6e4613b6b55.png">
<img width="1440" alt="Screen Shot 2020-05-06 at 11 30 27" src="https://user-images.githubusercontent.com/52497006/81162197-15601300-8f8d-11ea-974a-bbd9efb75880.png">

#### Questions:
- N/A

2020-05-06 12:45 UTC, santiago-rodrig commented
## Pull Request under review by @santiago-rodrig (TSE)

2020-05-06 13:01 UTC, santiago-dev96 requested changes
# Changes required :no_good_man: 
1. Your icons are not in the correct order (yes, it is a requirement)

![image](https://user-images.githubusercontent.com/43162770/81179612-e7bc9f00-8f77-11ea-92d6-8182c0f5c648.png)

2. Your form is not centered, I suggested some changes regarding that.

Please submit another CRR (Code Review Request) after implementing the changes. Have a nice day :wave:

2020-05-06 13:01 UTC, santiago-dev96 commented on css/index.css
> +  position: center;
The `position` property is not being properly used, you should read about the property [here](https://developer.mozilla.org/en-US/docs/Web/CSS/position).
```suggestion
  margin: 30px auto 50px auto;
```

2020-05-06 13:01 UTC, santiago-dev96 commented on index.html
> +                <div><a href="#"> <img src="./images/icon3.svg" width="23" height="23" alt=""/></a></div>
I think the alt should have some content; if it doesn't have any then it is useless for the visually impaired people. Also, your icons are untidy.
```suggestion
                <div><a href="#"> <img src="./images/icon2.svg" width="23" height="23" alt="turbotax logo"/></a></div>
```

2020-05-06 13:01 UTC, santiago-dev96 commented on index.html
> +                <div><a href="#"> <img src="./images/icon2.svg" width="23" height="23" alt="" /></a></div>
```suggestion
                <div><a href="#"> <img src="./images/icon1.svg" width="23" height="23" alt="quickbooks logo" /></a></div>
```

2020-05-06 13:01 UTC, santiago-dev96 commented on index.html
> +                <div><a href="#"><img src="./images/icon1.svg" width="23" height="23" alt="" /></a> </div>
```suggestion
                <div><a href="#"><img src="./images/icon3.svg" width="23" height="23" alt="mint logo" /></a> </div>
```

2020-05-06 13:41 UTC, mujohn26 commented
Hello @santiago-rodrig  thanks for the feedback and it was resolved.

2020-05-07 00:15 UTC, serdg0 requested changes
Hello @mujohn26 !

All the changes are good but still there is an issue. The intuit logo in the top of the form is not properly centered. I see you used a margin-left to try to center it, but I don't recommend it. I'm attaching the image.

![Selection_009](https://user-images.githubusercontent.com/49207642/81240681-afe04680-8fcd-11ea-9483-1eb3eef17705.png)

- [ ] Center main-logo. **HINT**: Use flex!.

**Happy Coding!** :computer: :nerd_face:

2020-05-07 05:57 UTC, mujohn26 commented
> Hello @mujohn26 !
> 
> All the changes are good but still there is an issue. The intuit logo in the top of the form is not properly centered. I see you used a margin-left to try to center it, but I don't recommend it. I'm attaching the image.
> 
> ![Selection_009](https://user-images.githubusercontent.com/49207642/81240681-afe04680-8fcd-11ea-9483-1eb3eef17705.png)
> 
> * [ ]  Center main-logo. **HINT**: Use flex!.
> 
> **Happy Coding!** 💻 🤓


Hello, @serdg0 Thanks for the feedback was really very helpful and it was resolved.

2020-05-07 23:34 UTC, lucasmazo32 approved these changes
# Project approved :rocket:

Great job on implementing the changes requested!

You can go ahead and merge this pull request.

### Happy coding! :computer:

## Lucas Mazo

2020-05-08 05:45 UTC, merged